name: Build ZSTD for DH

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Rename for DH
        run: bash ./renamer.sh
      - name: Apply CMake patches
        run: git apply ./patches/CMakeLists.patch
      - name: Change version for DH
        run: git apply ./patches/version.patch
      - name: Build
        run: ./gradlew :app:assembleRelease
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: zstd-dh-release
          path: app/build/outputs/aar/app-release.aar

