name: Build and Release all flavours

on:
  workflow_dispatch:

jobs:
  build-vanilla:
    name: Build vanilla ZSTD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: ./gradlew :app:assembleRelease
      - name: Rename artifact
        run: mv app/build/outputs/aar/app-release.aar app/build/outputs/aar/zstd-release.aar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zstd-vanilla
          path: app/build/outputs/aar/zstd-release.aar

  build-dh:
    name: Build ZSTD for DH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Rename for DH
        run: bash ./renamer.sh
      - name: Apply CMake patches
        run: git apply ./patches/CMakeLists.patch
      - name: Change version for DH
        run: git apply ./patches/version.patch
      - name: Build
        run: ./gradlew :app:assembleRelease
      - name: Rename artifact
        run: mv app/build/outputs/aar/app-release.aar app/build/outputs/aar/zstd-dh-release.aar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zstd-dh
          path: app/build/outputs/aar/zstd-dh-release.aar

  release:
    name: Release
    needs: [build-vanilla, build-dh]
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: out/
        - name: Upload Releases
          uses: softprops/action-gh-release@v3
          with:
            name: ZSTD-AAR Release ${{ github.run_number }}
            tag_name: zstd-aar-release-${{ github.run_number }}
            body: |
              ## ZSTD AAR release builds. 
              To download click on **▶Assets**, then choose the file you wish to download. You will need to unzip it to get the AAR.
              
              >Vanilla ZSTD build: `zstd-vanilla`<br>
              >DH renamed ZSTD build: `zstd-dh`
              
              Commit hash: ${{ github.sha }}
            files: |
              out/zstd-vanilla
              out/zstd-dh

